markdown: kramdown
highlighter: rouge
syntax_highlighter: rouge

excerpt_separator: <!--more-->

# Permalinks
permalink:        pretty

# Setup
title:            "Busy Beaver"
tagline:          "Kali's tape"
description:      'Results of long-lasting computations in a geeky brain'
url:              http://www.poumeyrol.fr

author:
  name:           'Mathieu Poumeyrol'
  url:              http://www.poumeyrol.fr

# Custom vars
#version:          2.0.0

gems: [jekyll-paginate]
paginate: 5

kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false

