# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            "Busy Beaver"
tagline:          "Kali's tape"
description:      'Results of long-lasting computations in a geeky brain'
url:              http://www.poumeyrol.fr

author:
  name:           'Mathieu Poumeyrol'
  url:              http://www.poumeyrol.fr

paginate:         5

# Custom vars
version:          2.0.0

#github:
#  repo:           https://github.com/poole/hyde

gems: [jekyll-paginate]

redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data"]

